In [264]:
from bs4 import BeautifulStoneSoup
import requests
import json
import pandas as pd
import numpy as np

In [294]:
URL = 'https://api.yelp.com/v3/businesses/search'
API_KEY = '3TjUrfMsEdbVfUKeiU31J7vFJyZp20FKhSg_OJni2TOL_Lo8A9-Z0WG_T3_jFeGzh3-WBtszKN1AAFPuYLh-7mJ7sxP2YdMalw_D5y4ExcXL3c0xUST3Sp-OIGMvXXYx'

params = {'location': 'NYC', 
           'limit': 50}

headers = {'Authorization': 'bearer %s' % API_KEY}
res = requests.get(url=URL, params = params, headers = headers)

In [295]:
res.status_code

200

In [306]:
data['businesses'][0]

{'id': 'H4jJ7XB3CetIr1pg56CczQ',
 'alias': 'levain-bakery-new-york',
 'name': 'Levain Bakery',
 'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/jCdrXah--NjPaOLb-30BUw/o.jpg',
 'is_closed': False,
 'url': 'https://www.yelp.com/biz/levain-bakery-new-york?adjust_creative=_dOL2tQEZNA2cv5pnszrdw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=_dOL2tQEZNA2cv5pnszrdw',
 'review_count': 7629,
 'categories': [{'alias': 'bakeries', 'title': 'Bakeries'}],
 'rating': 4.5,
 'coordinates': {'latitude': 40.7799404643263, 'longitude': -73.980282552649},
 'transactions': [],
 'price': '$$',
 'location': {'address1': '167 W 74th St',
  'address2': '',
  'address3': '',
  'city': 'New York',
  'zip_code': '10023',
  'country': 'US',
  'state': 'NY',
  'display_address': ['167 W 74th St', 'New York, NY 10023']},
 'phone': '+19174643769',
 'display_phone': '(917) 464-3769',
 'distance': 8367.197123060287}

In [299]:
data = res.json()

In [302]:
data['businesses'][0]['price']

'$$'

In [310]:
df = []
for i in range(30):
    params = {'location': 'NYC', 
           'limit': 50, 
           'offset': (50 * i)}
    res = requests.get(url=URL, params = params, headers = headers)
    data = res.json()
    df.append(data)

In [317]:
yelp = []
for i in df[0]['businesses']:
    try:
        item = {}
        item['name'] = i['name']
        item['review_count'] = i['review_count']
        item['categories'] = i['categories'][0]['title']
        item['price'] = i['price']
        item['city'] = i['location']['city']
        item['zip_code'] = i['location']['zip_code']
        yelp.append(item)
    except:
        pass

In [315]:
df[0].keys()

dict_keys(['businesses', 'total', 'region'])

In [308]:
for i in data['businesses']:
    print(i['name'])

Levain Bakery
The Halal Guys
Ippudo NY
Katz's Delicatessen
The Metropolitan Museum of Art
Central Park
Bibble & Sip
Los Tacos No.1
Burger & Lobster
Gramercy Tavern
Best Bagel & Coffee
LoveMama
The High Line
Doughnut Plant
Peter Luger
Prince Street Pizza
National September 11 Memorial Museum
Shake Shack
Clinton Street Baking Company
Thai Villa
Le Bernardin
Brooklyn Bridge
Two Little Red Hens
Dominique Ansel Bakery
Buddakan
Taiyaki NYC
Am√©lie
Juliana's Pizza
Club A Steakhouse
Russ & Daughters
Joe's Shanghai
Jacob's Pickles
Eataly NYC Flatiron
Chinatown Ice Cream Factory
Totto Ramen
Eleven Madison Park
Lombardi's Pizza
Del Frisco's Double Eagle Steakhouse
Ippudo Westside
Spot Dessert Bar
Upstate
Dough
Grand Central Terminal
Los Tacos No.1
Caracas Arepa Bar
ABC Kitchen
Rice To Riches
Angel's Share
Traif
Molly's Cupcakes

In [318]:
pd.DataFrame(yelp)

,categories,city,name,price,review_count,zip_code
0,Bakeries,New York,Levain Bakery,$$,7629,10023
1,Food Stands,New York,The Halal Guys,$,9212,10019
2,Ramen,New York,Ippudo NY,$$,9792,10003
3,Delis,New York,Katz's Delicatessen,$$,11416,10003
4,Coffee & Tea,New York,Bibble & Sip,$,4480,10019
5,Tacos,New York,Los Tacos No.1,$,2738,10011
6,Seafood,New York,Burger & Lobster,$$,5170,10011
7,American (New),New York,Gramercy Tavern,$$$$,2781,10003
8,Bagels,New York,Best Bagel & Coffee,$,2951,10001
9,Thai,New York,LoveMama,$$,4361,10003
10,Donuts,New York,Doughnut Plant,$$,3151,10002
11,Steakhouses,Brooklyn,Peter Luger,$$$$,5437,11211
12,Pizza,New York,Prince Street Pizza,$,2911,10012
13,Burgers,New York,Shake Shack,$$,5533,10010
14,Bakeries,New York,Clinton Street Baking Company,$$,4747,10002
15,Thai,New York,Thai Villa,$$,2696,10003
16,French,New York,Le Bernardin,$$$$,2422,10019
17,Bakeries,New York,Two Little Red Hens,$$,2467,10028
18,Bakeries,New York,Dominique Ansel Bakery,$$,4235,10012
19,Chinese,New York,Buddakan,$$$,3799,10011
20,Ice Cream & Frozen Yogurt,New York,Taiyaki NYC,$,2631,10013
21,French,New York,Am√©lie,$$,2508,10011
22,Pizza,Brooklyn,Juliana's Pizza,$$,2014,11201
23,Steakhouses,New York,Club A Steakhouse,$$$,2621,10022
24,Bagels,New York,Russ & Daughters,$$,2030,10002
25,Shanghainese,New York,Joe's Shanghai,$$,5833,10013
26,Comfort Food,New York,Jacob's Pickles,$$,3799,10024
27,Italian,New York,Eataly NYC Flatiron,$$,5307,10010
28,Ice Cream & Frozen Yogurt,New York,Chinatown Ice Cream Factory,$,2648,10013
29,Ramen,New York,Totto Ramen,$$,5308,10019
30,American (New),New York,Eleven Madison Park,$$$$,2052,10010
31,Pizza,New York,Lombardi's Pizza,$$,5894,10012
32,Steakhouses,New York,Del Frisco's Double Eagle Steakhouse,$$$$,2822,10020
33,Ramen,New York,Ippudo Westside,$$,3520,10019
34,Desserts,New York,Spot Dessert Bar,$$,2828,10003
35,Seafood,New York,Upstate,$$,1748,10003
36,Donuts,Brooklyn,Dough,$,1699,11205
37,Tacos,New York,Los Tacos No.1,$,1294,10036
38,Venezuelan,New York,Caracas Arepa Bar,$$,2528,10009
39,American (New),New York,ABC Kitchen,$$$,2886,10003
40,Desserts,New York,Rice To Riches,$$,2952,10012
41,Cocktail Bars,New York,Angel's Share,$$,2041,10003
42,American (New),Brooklyn,Traif,$$$,1821,11211
43,Bakeries,New York,Molly's Cupcakes,$$,1620,10014

In [268]:
data['businesses'][0]

{'id': 'H4jJ7XB3CetIr1pg56CczQ',
 'alias': 'levain-bakery-new-york',
 'name': 'Levain Bakery',
 'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/jCdrXah--NjPaOLb-30BUw/o.jpg',
 'is_closed': False,
 'url': 'https://www.yelp.com/biz/levain-bakery-new-york?adjust_creative=_dOL2tQEZNA2cv5pnszrdw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=_dOL2tQEZNA2cv5pnszrdw',
 'review_count': 7629,
 'categories': [{'alias': 'bakeries', 'title': 'Bakeries'}],
 'rating': 4.5,
 'coordinates': {'latitude': 40.7799404643263, 'longitude': -73.980282552649},
 'transactions': [],
 'price': '$$',
 'location': {'address1': '167 W 74th St',
  'address2': '',
  'address3': '',
  'city': 'New York',
  'zip_code': '10023',
  'country': 'US',
  'state': 'NY',
  'display_address': ['167 W 74th St', 'New York, NY 10023']},
 'phone': '+19174643769',
 'display_phone': '(917) 464-3769',
 'distance': 8367.197123060287}